/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as DescobrirRouteImport } from './routes/descobrir'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogadorIdRouteImport } from './routes/jogador.$id'
import { Route as DashboardScoutRouteImport } from './routes/dashboard.scout'
import { Route as DashboardJogadorRouteImport } from './routes/dashboard.jogador'
import { Route as ClubeIdRouteImport } from './routes/clube.$id'

const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const DescobrirRoute = DescobrirRouteImport.update({
  id: '/descobrir',
  path: '/descobrir',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadorIdRoute = JogadorIdRouteImport.update({
  id: '/jogador/$id',
  path: '/jogador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScoutRoute = DashboardScoutRouteImport.update({
  id: '/dashboard/scout',
  path: '/dashboard/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardJogadorRoute = DashboardJogadorRouteImport.update({
  id: '/dashboard/jogador',
  path: '/dashboard/jogador',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeIdRoute = ClubeIdRouteImport.update({
  id: '/clube/$id',
  path: '/clube/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/descobrir': typeof DescobrirRoute
  '/precos': typeof PrecosRoute
  '/clube/$id': typeof ClubeIdRoute
  '/dashboard/jogador': typeof DashboardJogadorRoute
  '/dashboard/scout': typeof DashboardScoutRoute
  '/jogador/$id': typeof JogadorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/descobrir': typeof DescobrirRoute
  '/precos': typeof PrecosRoute
  '/clube/$id': typeof ClubeIdRoute
  '/dashboard/jogador': typeof DashboardJogadorRoute
  '/dashboard/scout': typeof DashboardScoutRoute
  '/jogador/$id': typeof JogadorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/descobrir': typeof DescobrirRoute
  '/precos': typeof PrecosRoute
  '/clube/$id': typeof ClubeIdRoute
  '/dashboard/jogador': typeof DashboardJogadorRoute
  '/dashboard/scout': typeof DashboardScoutRoute
  '/jogador/$id': typeof JogadorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparar'
    | '/descobrir'
    | '/precos'
    | '/clube/$id'
    | '/dashboard/jogador'
    | '/dashboard/scout'
    | '/jogador/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparar'
    | '/descobrir'
    | '/precos'
    | '/clube/$id'
    | '/dashboard/jogador'
    | '/dashboard/scout'
    | '/jogador/$id'
  id:
    | '__root__'
    | '/'
    | '/comparar'
    | '/descobrir'
    | '/precos'
    | '/clube/$id'
    | '/dashboard/jogador'
    | '/dashboard/scout'
    | '/jogador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompararRoute: typeof CompararRoute
  DescobrirRoute: typeof DescobrirRoute
  PrecosRoute: typeof PrecosRoute
  ClubeIdRoute: typeof ClubeIdRoute
  DashboardJogadorRoute: typeof DashboardJogadorRoute
  DashboardScoutRoute: typeof DashboardScoutRoute
  JogadorIdRoute: typeof JogadorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descobrir': {
      id: '/descobrir'
      path: '/descobrir'
      fullPath: '/descobrir'
      preLoaderRoute: typeof DescobrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogador/$id': {
      id: '/jogador/$id'
      path: '/jogador/$id'
      fullPath: '/jogador/$id'
      preLoaderRoute: typeof JogadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scout': {
      id: '/dashboard/scout'
      path: '/dashboard/scout'
      fullPath: '/dashboard/scout'
      preLoaderRoute: typeof DashboardScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/jogador': {
      id: '/dashboard/jogador'
      path: '/dashboard/jogador'
      fullPath: '/dashboard/jogador'
      preLoaderRoute: typeof DashboardJogadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/$id': {
      id: '/clube/$id'
      path: '/clube/$id'
      fullPath: '/clube/$id'
      preLoaderRoute: typeof ClubeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompararRoute: CompararRoute,
  DescobrirRoute: DescobrirRoute,
  PrecosRoute: PrecosRoute,
  ClubeIdRoute: ClubeIdRoute,
  DashboardJogadorRoute: DashboardJogadorRoute,
  DashboardScoutRoute: DashboardScoutRoute,
  JogadorIdRoute: JogadorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
